apiVersion: v1
kind: Service
metadata:
  labels:
    app: blog-admin
  name: blog-admin
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: blog-admin
  type: NodePort