import type { NextPage } from "next";
import Head from "next/head";
import { SidebarWithHeader } from "../components/side-with-header";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin/favicon.ico" />
      </Head>
      <SidebarWithHeader />
    </div>
  );
};

export default Home;
