import type { NextPage } from "next";
import Head from "next/head";
import { SidebarWithHeader } from "../components/sidebar-with-header";
import { Box } from "@chakra-ui/react";
import { Editor } from "../components/editor";
import { sdk } from "../lib/graphql-client";
import { useEffect, useState } from "react";

const Home: NextPage = () => {
  const [slugs, setSlugs] = useState([] as string[]);
  useEffect(() => {
    async function getSlugs() {
      const slugsQuery = await sdk.slugs();
      const slugs = slugsQuery.posts.map((post) => {
        return post.slug;
      });
      setSlugs(slugs);
    }
    getSlugs().catch((error) => {
      console.error(error);
    });
  }, [slugs]);

  return (
    <Box>
      <Head>
        <title>Blog Admin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/admin/favicon.ico" />
      </Head>
      <SidebarWithHeader slugs={slugs}>
        <Editor />
      </SidebarWithHeader>
    </Box>
  );
};

export default Home;
